//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoTVCorporativa
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsContentXml
    {
        public cmsContentXml()
        {
            this.NoticiaTVCorporativaHistorico = new HashSet<NoticiaTVCorporativaHistorico>();
            this.SlidersTVCorporativaHistorico = new HashSet<SlidersTVCorporativaHistorico>();
            this.VideosTvCorporativaHistorico = new HashSet<VideosTvCorporativaHistorico>();
        }
    
        public int nodeId { get; set; }
        public string xml { get; set; }
    
        public virtual ICollection<NoticiaTVCorporativaHistorico> NoticiaTVCorporativaHistorico { get; set; }
        public virtual ICollection<SlidersTVCorporativaHistorico> SlidersTVCorporativaHistorico { get; set; }
        public virtual ICollection<VideosTvCorporativaHistorico> VideosTvCorporativaHistorico { get; set; }
    }
}
