//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoTVCorporativa
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticiaCanalEnergiaHistorico
    {
        public int id { get; set; }
        public Nullable<int> idNoticiaCanalEnergia { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string canal { get; set; }
        public string titulo { get; set; }
        public string conteudo { get; set; }
        public string urlImagem { get; set; }
    }
}
