//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoTVCorporativa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvQueirozGalvaoConteudoTipo
    {
        public tvQueirozGalvaoConteudoTipo()
        {
            this.tvQueirozGalvaoConteudo = new HashSet<tvQueirozGalvaoConteudo>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<tvQueirozGalvaoConteudo> tvQueirozGalvaoConteudo { get; set; }
    }
}
