//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoTVCorporativa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvQueirozGalvaoConteudo
    {
        public tvQueirozGalvaoConteudo()
        {
            this.tvQueirozGalvaoConteudoSlider = new HashSet<tvQueirozGalvaoConteudoSlider>();
        }
    
        public int id { get; set; }
        public Nullable<int> tvQueirozGalvaoConteudoTipoId { get; set; }
        public Nullable<int> ordem { get; set; }
        public Nullable<System.DateTime> dataInicial { get; set; }
        public Nullable<System.DateTime> dataFinal { get; set; }
        public string canal { get; set; }
        public string titulo { get; set; }
        public string conteudo { get; set; }
        public string urlImagem { get; set; }
        public string urlVideo { get; set; }
        public Nullable<int> tempoExibicao { get; set; }
        public Nullable<bool> flExibido { get; set; }
    
        public virtual ICollection<tvQueirozGalvaoConteudoSlider> tvQueirozGalvaoConteudoSlider { get; set; }
        public virtual tvQueirozGalvaoConteudoTipo tvQueirozGalvaoConteudoTipo { get; set; }
    }
}
