//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoTVCorporativa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvQueirozGalvaoConteudoSlider
    {
        public int id { get; set; }
        public int tvQueirozGalvaoConteudoId { get; set; }
        public Nullable<System.DateTime> dataInicial { get; set; }
        public Nullable<System.DateTime> dataFinal { get; set; }
        public string canal { get; set; }
        public string titulo { get; set; }
        public string urlImagem { get; set; }
        public Nullable<int> tempoExibicao { get; set; }
        public string subtitulo { get; set; }
    
        public virtual tvQueirozGalvaoConteudo tvQueirozGalvaoConteudo { get; set; }
    }
}
